### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by AlexSidDev** [PeterWang512/GANWarping#1]
Hello! I successfully downloaded training data, but when I'm trying to download pretrained models and weights I got "500 Internal Server Error". After that I was trying to download training data again, to ensure that the problem is only with models and weights, but now I can't downloaded even training data because of Internal Server Error.

**Comment by PeterWang512** [comment]
Can you try it again and see if it works? It should be fixed now, thanks!

**Comment by AlexSidDev** [comment]
> Can you try it again and see if it works? It should be fixed now, thanks!

Yes, it works, thank you)
